trailingComma: 'es5'
tabWidth: 4
semi: true
singleQuote: true
useTabs: true
overrides:
  - files: ['*.yaml', '*.yml']
    options:
      tabWidth: 2
  - files: '*.json'
    options:
      tabWidth: 2
  - files: '*.code-workspace'
    options:
      tabWidth: 2
